services:
  auth-service:
    image: auth-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:8080"
    env_file:
      - .env         
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - GIN_MODE=${GIN_MODE}
      - PROJECT_URL=${PROJECT_URL}
    restart: unless-stopped
