version: '3.8'

services:
  story-service:
    image: story-service:latest
    build:
      context: ./story-service
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - JWT_SECRET=${JWT_SECRET}
    restart: unless-stopped
